# Generated by Django 3.0.7 on 2021-01-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
