# Generated by Django 3.0.7 on 2021-01-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_article_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True),
        ),
    ]
