# Generated by Django 3.0.7 on 2021-01-15 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0004_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.FileField(blank=True, null=True, upload_to='')),
                ('last_name', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.FileField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.EmailField(blank=True, max_length=50, null=True)),
                ('city', models.EmailField(blank=True, max_length=50, null=True)),
                ('location', models.EmailField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
