# Generated by Django 3.0.7 on 2021-01-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210115_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
