# Generated by Django 3.0.7 on 2021-01-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
