# Generated by Django 3.0.7 on 2021-01-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210115_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
